# Generated by Django 3.2.4 on 2021-06-26 10:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('others', 'others'), ('canon', 'canon'), ('red', 'red'), ('fuji', 'fuji'), ('nikon', 'nikon'), ('sony', 'sony'), ('panasonic', 'panasonic')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('mobile_review', 'mobile_review'), ('code', 'code'), ('film_making', 'film_making'), ('cooking', 'cooking'), ('gaming', 'gaming'), ('vlogs', 'vlogs'), ('comedy', 'comedy')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('large', 'large'), ('solo', 'solo'), ('small', 'small')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
