# Generated by Django 3.2.4 on 2021-06-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210626_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('Red', 'Red'), ('Others', 'Others'), ('Fuji', 'Fuji'), ('Sony', 'Sony'), ('Nikon', 'Nikon'), ('Canon', 'Canon'), ('Panasonic', 'Panasonic')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('VLOGS', 'VLOGS'), ('GAMING', 'GAMING'), ('COOKING', 'COOKING'), ('SELF-IMPROVEMENT', 'SELF-IMPROVEMENT'), ('MOBILE_REVIEW', 'MOBILE_REVIEW'), ('CODE', 'CODE'), ('COMEDY', 'COMEDY'), ('FILM_MAKING', 'FILM_MAKING')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('small', 'small'), ('large', 'large'), ('solo', 'solo')], max_length=255),
        ),
    ]
