# Generated by Django 3.2.4 on 2021-06-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_auto_20210627_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('Nikon', 'Nikon'), ('Red', 'Red'), ('Sony', 'Sony'), ('Panasonic', 'Panasonic'), ('Fuji', 'Fuji'), ('Canon', 'Canon'), ('Others', 'Others')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('SELF-IMPROVEMENT', 'SELF-IMPROVEMENT'), ('MOBILE_REVIEW', 'MOBILE_REVIEW'), ('VLOGS', 'VLOGS'), ('FILM_MAKING', 'FILM_MAKING'), ('COMEDY', 'COMEDY'), ('COOKING', 'COOKING'), ('GAMING', 'GAMING'), ('CODE', 'CODE')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('large', 'large'), ('solo', 'solo'), ('small', 'small')], max_length=255),
        ),
    ]
