# Generated by Django 3.2.4 on 2021-07-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0005_auto_20210628_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('Canon', 'Canon'), ('Fuji', 'Fuji'), ('Others', 'Others'), ('Sony', 'Sony'), ('Red', 'Red'), ('Nikon', 'Nikon'), ('Panasonic', 'Panasonic')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('COMEDY', 'COMEDY'), ('MOBILE_REVIEW', 'MOBILE_REVIEW'), ('SELF-IMPROVEMENT', 'SELF-IMPROVEMENT'), ('CODE', 'CODE'), ('COOKING', 'COOKING'), ('VLOGS', 'VLOGS'), ('GAMING', 'GAMING'), ('FILM_MAKING', 'FILM_MAKING'), ('MUSIC', 'MUSIC')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large'), ('Solo', 'Solo')], max_length=255),
        ),
    ]
